spring:
  datasource:
    url: jdbc:mysql://59.110.163.243:3306/oil?characterEncoding=utf8&useSSL=false
    username: oil
    password: 690818
    #    username: root
    #    password: 690818
    test-while-idle: true
    validation-query: SELECT 1

    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd'T'HH:mm
  servlet:
    multipart:
      max-request-size: 1024Mb
      max-file-size: 500Mb
      enabled: true

doc:
  path: /home/waiter/logs